<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rules" nsURI="ecore://nasdanika.org/models/rules" nsPrefix="org.nasdanika.models.rules">
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suppress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="severity" lowerBound="1"
        eType="#//Severity" eOpposite="#//Severity/rules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Actions to be taken to address rule violations. Rule actions serve as documentation and as templates/prototypes for violation actions."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleSet" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//Domain">
    <eOperations name="resolve" eType="#//RuleSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//RuleSet" eOpposite="#//RuleSet/extensions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
        eType="#//RuleSet" eOpposite="#//RuleSet/extends"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//StringIdentity/id"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="severities" upperBound="-1"
        eType="#//Severity" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//StringIdentity/id">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogeneous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inspectable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inspectionResults" upperBound="-1"
        eType="#//InspectionResult" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="waivers" upperBound="-1"
        eType="#//Waiver" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InspectionResult" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//ArchitectureDescriptionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="#//Rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Violation" eSuperTypes="#//InspectionResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="waivers" upperBound="-1"
        eType="#//Waiver" eOpposite="#//Waiver/violations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Actions to be taken to address the violation"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure" eSuperTypes="#//InspectionResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cause" eType="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//Throwable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Waiver" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//ArchitectureDescriptionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="violations" upperBound="-1"
        eType="#//Violation" eOpposite="#//Violation/waivers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Severity" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//ArchitectureDescriptionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" eOpposite="#//Rule/severity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="../../org.nasdanika.models.architecture/model/architecture.ecore#//Node">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An action to be taken to address a rule violation"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceAction" eSuperTypes="#//Action">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An action on a resource identified by a string identifier, e.g. a path or URI"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resource identifier - path, URI, ..."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextResourceAction" eSuperTypes="#//ResourceAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryResourceAction" eSuperTypes="#//ResourceAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateResourceAction" eSuperTypes="#//ResourceAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateTextResourceAction" eSuperTypes="#//CreateResourceAction #//TextResourceAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateBinaryResourceAction" eSuperTypes="#//CreateResourceAction #//BinaryResourceAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteResourceAction" eSuperTypes="#//ResourceAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveResourceAction" eSuperTypes="#//ResourceAction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Moves (renames) the resources - changes its identifier"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="New identifier"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateResourceAction" eSuperTypes="#//ResourceAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateTextResourceAction" eSuperTypes="#//UpdateResourceAction #//TextResourceAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateBinaryResourceAction" eSuperTypes="#//UpdateResourceAction #//BinaryResourceAction"/>
  <eSubpackages name="java" nsURI="ecore://nasdanika.org/models/rules/java" nsPrefix="org.nasdanika.models.rules.java">
    <eClassifiers xsi:type="ecore:EClass" name="CompilationUnitAction" eSuperTypes="#//Action">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An action on a compilation unit"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateCompilationUnitAction" eSuperTypes="#//java/CompilationUnitAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnit" eType="ecore:EClass ../../org.nasdanika.models.java/model/java.ecore#//CompilationUnit"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteCompilationUnitAction" eSuperTypes="#//java/CompilationUnitAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnit" eType="ecore:EClass ../../org.nasdanika.models.java/model/java.ecore#//CompilationUnit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpdateCompilationUnitAction" eSuperTypes="#//java/CompilationUnitAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="compilationUnit" eType="ecore:EClass ../../org.nasdanika.models.java/model/java.ecore#//CompilationUnit"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
